#include "opengl_shader_definition.h"

const TextEditor::LanguageDefinition &opengl_shader_definition() {
  static bool inited = false;
  static TextEditor::LanguageDefinition langDef;
  if (!inited) {
    static const char *const keywords[] = {
        "attribute",
        "break",
        "buffer",
        "case",
        "centroid",
        "coherent",
        "const",
        "continue",
        "default",
        "discard",
        "do",
        "double",
        "dvec2",
        "dvec3",
        "dvec4",
        "else",
        "enum",
        "extern",
        "false",
        "flat",
        "float",
        "for",
        "highp",
        "if",
        "in",
        "inout",
        "int",
        "invariant",
        "ivec2",
        "ivec3",
        "ivec4",
        "layout",
        "lowp",
        "mat2",
        "mat2x2",
        "mat2x3",
        "mat2x4",
        "mat3",
        "mat3x2",
        "mat3x3",
        "mat3x4",
        "mat4",
        "mat4x2",
        "mat4x3",
        "mat4x4",
        "mediump",
        "noperspective",
        "out",
        "patch",
        "precision",
        "readonly",
        "restrict",
        "return",
        "sample",
        "shared",
        "smooth",
        "struct",
        "switch",
        "true",
        "uint",
        "uniform",
        "varying",
        "vec2",
        "vec3",
        "vec4",
        "void",
        "volatile",
        "while",
        "writeonly",
        "bvec2",
        "bvec3",
        "bvec4",
        "uvec2",
        "uvec3",
        "uvec4",
        "sampler1D",
        "sampler2D",
        "sampler3D",
        "samplerCube",
        "sampler1DShadow",
        "sampler2DShadow",
        "samplerCubeShadow",
        "sampler1DArray",
        "sampler2DArray",
        "sampler1DArrayShadow",
        "sampler2DArrayShadow",
        "sampler2DRect",
        "sampler2DRectShadow",
        "isampler1D",
        "isampler2D",
        "isampler3D",
        "isamplerCube",
        "isampler1DArray",
        "isampler2DArray",
        "isampler2DRect",
        "usampler1D",
        "usampler2D",
        "usampler3D",
        "usamplerCube",
        "usampler1DArray",
        "usampler2DArray",
        "usampler2DRect",
        "samplerBuffer",
        "isamplerBuffer",
        "usamplerBuffer",
        "sampler2DMS",
        "isampler2DMS",
        "usampler2DMS",
        "sampler2DMSArray",
        "isampler2DMSArray",
        "usampler2DMSArray",
        "image2D",
        "image3D",
        "imageCube",
        "image2DArray",
        "imageCubeArray",
        "imageBuffer",
        "iimage2D",
        "iimage3D",
        "iimageCube",
        "iimage2DArray",
        "iimageCubeArray",
        "iimageBuffer",
        "uimage2D",
        "uimage3D",
        "uimageCube",
        "uimage2DArray",
        "uimageCubeArray",
        "uimageBuffer",
        "atomic_uint",
        "subroutine",
        "common",
        "partition",
        "active",
        // tessellation shader keywords
        "isolines",
        "triangles",
        "quads",
        "equal_spacing",
        "fractional_even_spacing",
        "fractional_odd_spacing",
        "cw",
        "ccw",
        "point_mode",
        "vertices",
        // built in variables
        "gl_VertexID",
        "gl_InstanceID",
        "gl_Position",
        "gl_PatchVerticesIn",
        "gl_PrimitiveID",
        "gl_InvocationID",
        "gl_TessCoord",
        "gl_TessLevelInner",
        "gl_TessLevelOuter",
    };
    for (auto &k : keywords)
      langDef.mKeywords.insert(k);

    static const char *const identifiers[] = {
        "radians",
        "degrees",
        "sin",
        "cos",
        "tan",
        "asin",
        "acos",
        "atan",
        "sinh",
        "cosh",
        "tanh",
        "asinh",
        "acosh",
        "atanh",
        "pow",
        "exp",
        "log",
        "exp2",
        "log2",
        "sqrt",
        "inverseSqrt",
        "abs",
        "sign",
        "floor",
        "trunc",
        "round",
        "roundEven",
        "ceil",
        "fract",
        "mod",
        "modf",
        "min",
        "max",
        "clamp",
        "mix",
        "step",
        "smoothstep",
        "length",
        "distance",
        "dot",
        "cross",
        "normalize",
        "faceforward",
        "reflect",
        "refract",
        "matrixCompMult",
        "outerProduct",
        "transpose",
        "determinant",
        "inverse",
        "lessThan",
        "lessThanEqual",
        "greaterThan",
        "greaterThanEqual",
        "equal",
        "notEqual",
        "any",
        "all",
        "not",
        "bitfieldExtract",
        "bitfieldInsert",
        "bitfieldReverse",
        "bitCount",
        "findLSB",
        "findMSB",
        "uaddCarry",
        "usubBorrow",
        "umulExtended",
        "imulExtended",
        "texture",
        "textureSize",
        "textureQueryLod",
        "textureQueryLevels",
        "textureLod",
        "textureOffset",
        "textureLodOffset",
        "texelFetch",
        "texelFetchOffset",
        "textureProj",
        "textureProjOffset",
        "textureProjLod",
        "textureProjLodOffset",
        "textureGrad",
        "textureGradOffset",
        "textureProjGrad",
        "textureProjGradOffset",
        "textureGather",
        "textureGatherOffset",
        "textureGatherOffsets",
        "texture2D",
        "textureCube",
        "texture2DProj",
        "texture2DLod",
        "textureCubeLod",
        "texture2DProjLod",
        "texture3D",
        "texture2DArray",
        "texture2DArrayLod",
        "dFdx",
        "dFdy",
        "dFdxFine",
        "dFdyFine",
        "dFdxCoarse",
        "dFdyCoarse",
        "fwidth",
        "fwidthFine",
        "fwidthCoarse",
        "interpolateAtCentroid",
        "interpolateAtSample",
        "interpolateAtOffset",
        "atomicAdd",
        "atomicMin",
        "atomicMax",
        "atomicAnd",
        "atomicOr",
        "atomicXor",
        "atomicExchange",
        "atomicCompSwap",
        "imageLoad",
        "imageStore",
        "imageAtomicAdd",
        "imageAtomicMin",
        "imageAtomicMax",
        "imageAtomicAnd",
        "imageAtomicOr",
        "imageAtomicXor",
        "imageAtomicExchange",
        "imageAtomicCompSwap",
        "EmitVertex",
        "EndPrimitive",
        "barrier",
    };
    for (auto &i : identifiers) {
      TextEditor::Identifier id;
      id.mDeclaration = "Built-in function";
      langDef.mIdentifiers.insert(std::make_pair(std::string(i), id));
    }

    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "[ \\t]*#[ \\t]*[a-zA-Z_]+",
            TextEditor::PaletteIndex::Preprocessor));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "L?\\\"(\\\\.|[^\\\"])*\\\"", TextEditor::PaletteIndex::String));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "\\'\\\\?[^\\']\\'", TextEditor::PaletteIndex::CharLiteral));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)([eE][+-]?[0-9]+)?[fF]?",
            TextEditor::PaletteIndex::Number));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "[+-]?[0-9]+[Uu]?[lL]?[lL]?", TextEditor::PaletteIndex::Number));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "0[0-7]+[Uu]?[lL]?[lL]?", TextEditor::PaletteIndex::Number));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "0[xX][0-9a-fA-F]+[uU]?[lL]?[lL]?",
            TextEditor::PaletteIndex::Number));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "[a-zA-Z_][a-zA-Z0-9_]*", TextEditor::PaletteIndex::Identifier));
    langDef.mTokenRegexStrings.push_back(
        std::make_pair<std::string, TextEditor::PaletteIndex>(
            "[\\[\\]\\{\\}\\!\\%\\^\\&\\*\\(\\)\\-\\+\\=\\~\\|\\<\\>\\?\\/"
            "\\;\\,\\.]",
            TextEditor::PaletteIndex::Punctuation));

    langDef.mCommentStart = "/*";
    langDef.mCommentEnd = "*/";
    langDef.mSingleLineComment = "//";

    langDef.mCaseSensitive = true;
    langDef.mAutoIndentation = true;

    langDef.mName = "OpenGL Shader";

    inited = true;
  }
  return langDef;
}